name: RELEASE NUGET

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.5.0
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish NuGet packacges
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_COD_KEY }}
      run: chmod +x ./scripts/pack.sh && ./scripts/pack.sh
      shell: bash
