name: RELEASE NUGET

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish NuGet packacges
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_COD_KEY }}
      run: chmod +x ./scripts/pack.sh && ./scripts/pack.sh
      shell: bash
